#!/bin/bash
cd /run/media/youssef/all_data/Music

mkdir -p "3ab3az"
mkdir -p "Abo El Anwar"
mkdir -p "Abyusif"
mkdir -p "Adele"
mkdir -p "Afroto"
mkdir -p "Ahmed Kamel"
mkdir -p "Ahmed Mekky"
mkdir -p "Ahmed Santa"
mkdir -p "Amir Eid"
mkdir -p "Amr Diab"
mkdir -p "Arsenik"
mkdir -p "Batistuta"
mkdir -p "Billie Eilish"
mkdir -p "Cairokee"
mkdir -p "DizzyTooShkinny"
mkdir -p "DJ Snake"
mkdir -p "Dj Totti"
mkdir -p "Double Zuksh"
mkdir -p "Dua Lipa"
mkdir -p "El Joker"
mkdir -p "El Waili"
mkdir -p "Eminem"
mkdir -p "Flex"
mkdir -p "Husayn"
mkdir -p "Lege-Cy"
mkdir -p "Lil Baba"
mkdir -p "Lil Noby"
mkdir -p "lisa"
mkdir -p "Mahmoud El Esseily"
mkdir -p "Marwan Moussa"
mkdir -p "Marwan Pablo"
mkdir -p "Mousv"
mkdir -p "Muhab"
mkdir -p "Muslim"
mkdir -p "Muslimm"
mkdir -p "Olivia Rodrigo"
mkdir -p "Shab jdeed"
mkdir -p "Shahyn"
mkdir -p "Sharmoofers"
mkdir -p "Shehab"
mkdir -p "Sia"
mkdir -p "Taylor Swift"
mkdir -p "Wegz"
mkdir -p "Wingii"
mkdir -p "XXXTENTACION"
mkdir -p "صموئيل فاروق"
mkdir -p "Black Pink"
mkdir -p "Youssef Joker"
mkdir -p "Bebe Rexha"
mkdir -p "Nicki Minaj"
mkdir -p "Ariana grande"

# mkdir -p "name-of-artist"



cd "3ab3az"
spotdl download https://open.spotify.com/artist/1L2TmL1IEbktDOsTtAy6sr?si=Y5WC_RWRSl6yA9F3FRxXQQ
cd ..
cd "Abo El Anwar"
spotdl download https://open.spotify.com/artist/2H6XYL9D5Z3ErkxCD0gmD6?si=c9ja8Wh6Qqek4j_0-inF-g
cd .. 
cd "Abyusif"
spotdl download https://open.spotify.com/artist/4o6vIkdmHiEXZOesrJj3KO?si=BOhQDf_CR4WK9xDaoCWQtQ
cd ..
cd "Adele"
spotdl download https://open.spotify.com/artist/4dpARuHxo51G3z768sgnrY?si=rIC_7jQXTJy_PpiDbVn1hA
cd ..
cd "Afroto"
spotdl download https://open.spotify.com/artist/7yBuSjd5Z3w7acodk51evR?si=_6MrteV0QG-kFzFzH6y7kA
cd ..
cd "Ahmed Kamel"
spotdl download https://open.spotify.com/artist/41g2nSmocqVLuYnmndxefu?si=Q9uVv85sReiL-vOnG8hKow
cd ..
cd "Ahmed Mekky"
spotdl download https://open.spotify.com/artist/6Q0JYiqcSa28nT0KOQZtX6?si=uHFucva8Q_SYwvo2r9Toiw
cd ..
cd "Ahmed Santa"
spotdl download https://open.spotify.com/artist/2jRxGTrLGVw35yRsElgsXj?si=8wZwWBXmS4aiOfntLPzgFw
cd ..
cd "Amir Eid"
spotdl download https://open.spotify.com/artist/1dYkjdBHkbyolcShgkh2Vp?si=wdKBViNxSR2Dnz3VhS22Iw
cd ..
cd "Arsenik"
spotdl download https://open.spotify.com/artist/2temuX6O0rZk6lw9anAYoM?si=ivOCdcB7TcSaGPVjjati-A
cd ..
cd "Batistuta"
spotdl download https://open.spotify.com/artist/5YqgTnXXqASob6AejLOCVo?si=PDhqGinfR2CMvAR4dABa1w
cd ..
cd "Billie Eilish"
spotdl download https://open.spotify.com/artist/6qqNVTkY8uBg9cP3Jd7DAH?si=sWyBjg_uTgC7fIC-LJpw7A
cd ..
cd "Cairokee"
spotdl download https://open.spotify.com/artist/2GVksDv9UpY60i4CvytrZK?si=9rNXsBoPR9eJotU9S-lP7Q
cd ..
cd "DizzyTooShkinny"
spotdl download https://open.spotify.com/artist/0QDlkRZ349RXtT5XcwcLRP?si=P5lqFtZ0SmiFNWBGNXnC8A
cd ..
cd "DJ Snake"
spotdl download https://open.spotify.com/artist/540vIaP2JwjQb9dm3aArA4?si=lVImWpTYRE-iPM8pUF_8Vw
cd ..
cd "Dj Totti"
spotdl download https://open.spotify.com/artist/6sm3nTKVNrdKN3iAo73oda?si=3nvL6zoaToirI15wngtPZA
cd ..
cd "Double Zuksh"
spotdl download https://open.spotify.com/artist/02T4vKIGje48LHpXmJoEwo?si=fpJjwBpsSLGG9UZ-gzVYIQ
cd ..
cd "Dua Lipa"
spotdl download https://open.spotify.com/artist/6M2wZ9GZgrQXHCFfjv46we?si=KFxZc6wzSq-asBf-6JAjkQ
cd ..
cd "El Joker"
spotdl download https://open.spotify.com/artist/0CXSHigx5x1U6jMhrNJkm0?si=WMgMUaAvRvKpr9aJV1JE6w
cd ..
cd "El Waili"
spotdl download https://open.spotify.com/artist/0OUma98suuyyJqFHtjX5oU?si=g4P4VepDRR2toystRl-eYg
cd ..
cd "Eminem"
spotdl download https://open.spotify.com/artist/7dGJo4pcD2V6oG8kP0tJRR?si=6nHIsKTqTriFhJHa2qlodA
cd ..
cd "Flex"
spotdl download https://open.spotify.com/artist/4rACOXTxSYqwgynYKJJpDX?si=AmdnMqU9SA6TXXe-b0Yfzg
cd ..
cd "Husayn"
spotdl download https://open.spotify.com/artist/388NKDhzE7FJ40ODmOr7aI?si=2IsET_J6TxidDVQoADHbzA
cd ..
cd "Lege-Cy"
spotdl download https://open.spotify.com/artist/6FJeuwLBCX8VSTf6hp1Vc9?si=eNP333GhSJqoonMbZgI7sw
cd ..
cd "Lil Baba"
spotdl download https://open.spotify.com/artist/0BoBtCqcbWMR0aa64eUuUa?si=pjSEAOubTxKhSDDLx17l6A
cd ..
cd "Lil Noby"
spotdl download https://open.spotify.com/artist/2kBJzh6V4KIom3bIhvMBHa?si=oe6bAVIxTCyMD0arF2ISuw
cd ..
cd "lisa"
spotdl download https://open.spotify.com/artist/5L1lO4eRHmJ7a0Q6csE5cT?si=OPa9yNtkRWK71ByJJynL_A
cd ..
cd "Mahmoud El Esseily"
spotdl download https://open.spotify.com/artist/7MGFOSQK8O3im8YslR3DLB?si=vqzNcYKRT8mV_Mslxib7fQ
cd ..
cd "Marwan Moussa"
spotdl download https://open.spotify.com/artist/2BBnFUgIaLHqoRYPfshoPb?si=ARrsmzz-Rhyp7YQVmIHBZQ
cd ..
cd "Marwan Pablo"
spotdl download https://open.spotify.com/artist/56chSp36PsMhpQvUn1kdR3?si=yQg_Pl20RqK6n0nTDfaC8A
cd ..
cd "Mousv"
spotdl download https://open.spotify.com/artist/6CGE1o9Swi1tAEa23wRTah?si=ALMqcIoFRYenjzXSYVbFxA
cd ..
cd "Muhab"
spotdl download https://open.spotify.com/artist/3mUUUQDWnVlttF1yERxmPQ?si=P0BoAZYuTFi9kNqQRSxjTw
cd ..
cd "Muslim"
spotdl download https://open.spotify.com/artist/2jOaCmspCCEhX27gTNSxnD?si=sTD5-aq-RCmUslkTakoSww
cd ..
cd "Muslimm"
spotdl download https://open.spotify.com/artist/2PM82jOCB674w4BL08zFVS?si=SmCGv6hcTCKYtrnjqhAPhg
cd ..
cd "Olivia Rodrigo"
spotdl download https://open.spotify.com/artist/1McMsnEElThX1knmY4oliG?si=9xtc0_SuRPaovfg1j44Lhw
cd ..
cd "Shab jdeed"
spotdl download https://open.spotify.com/artist/0KJ7DiybcwyulZLILX3Z95?si=aXw9F-85RHeUcuZIMoMd9w
cd ..
cd "Shahyn"
spotdl download https://open.spotify.com/artist/3SMvE0QyULRkKy2Y2FLbUG?si=C1IzrbuFSbOdH7adh50xzw
cd ..
cd "Sharmoofers"
spotdl download https://open.spotify.com/artist/0qZ24TkLCHoE3ajCzGItJ1?si=zEeEHRAkQW2hXcQhgDJh2Q
cd ..
cd "Shehab"
spotdl download https://open.spotify.com/artist/5764EiAfWT26wi1CdLcnwz?si=jT2VXvvJR5OdjsT7CuvGOQ
cd ..
cd "Sia"
spotdl download https://open.spotify.com/artist/5WUlDfRSoLAfcVSX1WnrxN?si=k15s4yOpT-Guf4Mr-acv2w
cd ..
cd "Taylor Swift"
spotdl download https://open.spotify.com/artist/06HL4z0CvFAxyc27GXpf02?si=mFDu943VRje--ReDn4_xNw
cd ..
cd "Wegz"
spotdl download https://open.spotify.com/artist/4BKC2HOGEqtYz2Xbgp9N1q?si=oU_8RVDrR3qv9vN7xzFFhQ
cd ..
cd "Wingii"
spotdl download https://open.spotify.com/artist/3i5MnWpawRCC9SYhLIHP7W?si=POz4CKIoTFi9HZ0Cskd3Ng
cd ..
cd "XXXTENTACION"
spotdl download https://open.spotify.com/artist/15UsOTVnJzReFVN1VCnxy4?si=0nix5eC1TTi4KIilYSgyEA
cd ..
cd "صموئيل فاروق"
spotdl download  https://open.spotify.com/artist/3iOkQyfRKJ1zwOxyNCJLUB?si=YQrjJpPFQQe4DxFPwkwcWQ
cd ..
cd "Black Pink"
spotdl download https://open.spotify.com/artist/41MozSoPIsD1dJM0CLPjZF?si=7CNIxqgARwWgpgUPWmB8AQ
cd ..
cd "Youssef Joker"
spotdl download https://open.spotify.com/artist/7eUTopJnyg62OYHCuHi3rw?si=XSad29nuRh2mIHLhK3W0ag
cd ..
cd "Bebe Rexha"
spotdl download https://open.spotify.com/artist/64M6ah0SkkRsnPGtGiRAbb?si=bqzKNXMOSaWmQUfkwex1Yw
cd ..
cd "Nicki Minaj"
spotdl download https://open.spotify.com/artist/0hCNtLu0JehylgoiP8L4Gh?si=85uMvaK9TcqZg_5PoFcLfQ
cd ..
cd "Ariana grande"
spotdl download https://open.spotify.com/artist/66CXWjxzNUsdJxJ2JdwvnR?si=lNpljidjTjiqXbI8Ccqcfg
cd ..
cd "Amr Diab"
spotdl download https://open.spotify.com/artist/5abSRg0xN1NV3gLbuvX24M?si=zdyi0h-JQU6QtsN0bnD86A
cd ..



# cd "name-of-artist"
# spotdl download "url"
# cd ..
